# GET http://localhost:3301/api/persons
# GET http://localhost:3301/info
# GET http://localhost:3301/api/persons/4
POST http://localhost:3301/api/persons
Content-Type: application/json

{
    "name": "Nitish Gupta"
    "number": 1234
}