POST http://localhost:3001/api/blogs
Content-Type: application/json

{
  "title": "blog with blogs part and user 2",
  "author": "Nitish gupta",
  "url": "blogs/1",
  "likes": 10
}
# POST http://localhost:3001/api/blogs
# Content-Type: application/json

# {
#   "title": "First blog",
#   "likes": 10
# }
# DELETE http://localhost:3001/api/blogs/5fa1794af285e3a34179da6c
# PUT http://localhost:3001/api/blogs/5fa17c5313b7f34d0054ed9a
# Content-Type: application/json

# {
#   "title": "First blog updated",
#   "author": "Nitish",
#   "url": "blogs/1",
#   "likes": 10
# }
# POST http://localhost:3001/api/users
# Content-Type: application/json

# {
#   "username": "gauetam",
#   "name": "gautam",
#   "password": "2"
# }