# GET http://localhost:3001/api/blogs
# POST http://localhost:3001/api/blogs
# Content-Type: application/json

# {
#   "title": "First blog",
#   "author": "Nitish",
#   "url": "blogs/1",
#   "likes": 10
# }
POST http://localhost:3001/api/blogs
Content-Type: application/json

{
  "title": "First blog",
  "likes": 10
}